name: Deployment

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

      - name: Generate Roboto
        run: msdf-bmfont -f https://github.com/google/fonts/raw/main/apache/roboto/static/Roboto-Regular.ttf -m 512,512 -o public/roboto-regular

      - name: Generate SourceSerifPro
        run: msdf-bmfont -f https://github.com/google/fonts/raw/main/ofl/sourceserifpro/SourceSerifPro-Regular.ttf -m 512,512 -o public/sourceserifpro-regular

      - name: Generate OpenSans
        run: msdf-bmfont -f https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans%5Bwdth%2Cwght%5D.ttf -m 512,512 -o public/opensans

      - name: Generate Montserrat
        run: msdf-bmfont -f https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat%5Bwght%5D.ttf -m 512,512 -o public/montserrat

      - name: Generate Quicksand
        run: msdf-bmfont -f https://github.com/google/fonts/raw/main/ofl/quicksand/Quicksand%5Bwght%5D.ttf -m 512,512 -o public/quicksand

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
