name: Deployment

on:
  push:
    branches: [main]

jobs:
  generate:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Install Font Forge
        run: sudo apt-get install -y fontforge;

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Copy LICENSE to public
        run: |
          cp LICENSE public/LICENSE

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

# Roboto

      - name: Generate Roboto Light
        run:  node scripts/download.js "Roboto" 300;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf roboto-light.ttf;
              npx msdf-bmfont -f json roboto-light.ttf -m 256,512 -o public/roboto-light -s 51

      - name: Generate Roboto Medium
        run:  node scripts/download.js "Roboto" 500;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf roboto.ttf;
              npx msdf-bmfont -f json roboto.ttf -m 256,512 -o public/roboto -s 51
      
      - name: Generate Roboto Bold
        run:  node scripts/download.js "Roboto" 700;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf roboto-bold.ttf;
              npx msdf-bmfont -f json roboto-bold.ttf -m 256,512 -o public/roboto-bold -s 51

# Open Sans

      - name: Generate Open Sans Light
        run:  node scripts/download.js "Open Sans" 300;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf opensans-light.ttf;
              npx msdf-bmfont -f json opensans-light.ttf -m 256,512 -o public/opensans-light -s 51

      - name: Generate Open Sans Medium
        run:  node scripts/download.js "Open Sans" 500;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf opensans.ttf;
              npx msdf-bmfont -f json opensans.ttf -m 256,512 -o public/opensans -s 51

      - name: Generate OpenSans Bold
        run:  node scripts/download.js "Open Sans" 700;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf opensans-bold.ttf;
              npx msdf-bmfont -f json opensans-bold.ttf -m 256,512 -o public/opensans-bold -s 51

# Inter

      - name: Generate Inter Light
        run:  node scripts/download.js "Inter" 300;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf inter-light.ttf;
              npx msdf-bmfont -f json inter-light.ttf -m 256,512 -o public/inter-light -s 51

      - name: Generate Inter Medium
        run:  node scripts/download.js "Inter" 500;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf inter.ttf;
              npx msdf-bmfont -f json inter.ttf -m 256,512 -o public/inter -s 51

      - name: Generate Inter Bold
        run:  node scripts/download.js "Inter" 700;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf inter-bold.ttf;
              npx msdf-bmfont -f json inter-bold.ttf -m 256,512 -o public/inter-bold -s 51

# Fira Code

      - name: Generate Fira Code Light
        run:  node scripts/download.js "Fira Code" 300;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf firacode-light.ttf;
              npx msdf-bmfont -f json firacode-light.ttf -m 256,512 -o public/firacode-light -s 51

      - name: Generate Fira Code Medium
        run:  node scripts/download.js "Fira Code" 500;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf firacode.ttf;
              npx msdf-bmfont -f json firacode.ttf -m 256,512 -o public/firacode -s 51

      - name: Generate Fira Code Bold
        run:  node scripts/download.js "Fira Code" 700;
              fontforge -lang=ff -c 'Open($1); SelectAll(); RemoveOverlap(); Generate($2)' font.ttf firacode-bold.ttf;
              npx msdf-bmfont -f json firacode-bold.ttf -m 256,512 -o public/firacode-bold -s 51
              

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
