name: Deployment

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

      - name: Install Font Forge
        run: sudo apt-get install software-properties-common; sudo add-apt-repository ppa:fontforge/fontforge; sudo apt-get update; sudo apt-get install fontforge;

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

      - name: Generate Roboto
        run:  npx download -o ./ --filename roboto.ttf https://github.com/openmaptiles/fonts/blob/master/roboto/Roboto-Regular.ttf?raw=true;
              fontforge -lang=ff -c 'Open($1); RemoveOverlap(); Generate($1)' roboto.ttf;
              npx msdf-bmfont -f json roboto.ttf -m 256,512 -o public/roboto -s 54

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
