name: Deployment

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

      - name: Generate Roboto
        run: npx download -o ./ --filename roboto.ttf https://github.com/openmaptiles/fonts/blob/master/roboto/Roboto-Regular.ttf?raw=true; npx msdf-bmfont -f json roboto.ttf -m 512,512 -o public/roboto

      - name: Generate SourceSerifPro
        run: npx download -o ./ --filename sourceserifpro.ttf  https://github.com/google/fonts/raw/main/ofl/sourceserifpro/SourceSerifPro-Regular.ttf; npx msdf-bmfont -f json sourceserifpro.ttf -m 512,512 -o public/sourceserifpro

      - name: Generate OpenSans
        run: npx download -o ./ --filename opensans.ttf https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans%5Bwdth%2Cwght%5D.ttf; npx msdf-bmfont -f json opensans.ttf -m 512,512 -o public/opensans

      - name: Generate Montserrat
        run: npx download -o ./ --filename montserrat.ttf https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat%5Bwght%5D.ttf; npx msdf-bmfont -f json montserrat.ttf -m 512,512 -o public/montserrat

      - name: Generate Quicksand
        run: npx download -o ./ --filename quicksand.ttf https://github.com/google/fonts/raw/main/ofl/quicksand/Quicksand%5Bwght%5D.ttf; npx msdf-bmfont -f json quicksand.ttf -m 512,512 -o public/quicksand

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
